# Copyright (c) 2011-2026 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0

COMMON_PATH = $(ESP_ROOT)/accelerators/rtl/common
COMMON_HLS_PATH = $(COMMON_PATH)/hls

include $(COMMON_HLS_PATH)/Makefile
